services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  fastapi:
    build: .
    command: ["uvicorn", "main:app", "--host=0.0.0.0", "--port", "8000", "--reload"]
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db